# Generated by Django 4.0.5 on 2024-12-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='dias_imagenes/')),
                ('texto', models.TextField(blank=True, null=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_mes', to='calendario.mes')),
            ],
        ),
    ]
